name: Auto release cherry-pick

on: 
  workflow_dispatch:
    inputs:
      PR-Number:
        description: 'The PR id you want to cherry-pick (e.g. 1608)'
        required: true
      target-base-branch:
        description: 'The target branch (e.g. release/s60)'
        required: true

jobs:
  cherry-pick-release:
    name: Create cherry-pick PR
    runs-on: ubuntu-latest

    steps:
    - name: Get source PR
      id: get-source-pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/srnbuse/automatic-bassoon/pulls/${{ github.event.inputs.PR-Number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Get commits for the pull requests
      id: get-commits
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/srnbuse/automatic-bassoon/pulls/${{ github.event.inputs.PR-Number }}/commits
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Download repo and checkout ${{ github.event.inputs.target-base-branch}}
      uses: actions/checkout@v2
      with:
        ref: ${{ fromJson(steps.get-source-pr.outputs.data).base.ref }}
        fetch-depth: 500

    - name: Get target branch name
      uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: '${{ github.event.inputs.target-base-branch}}'
        split-by: '/'
        
    - name: Replace dot with dashes in branch name
      uses: bluwy/substitute-string-action@v1
      id: findandreplace
      with:
        _input-text: ${{ steps.split.outputs._1 }}
        .: '-'

    - name: Create/Update branch from ${{ github.event.inputs.target-base-branch }}
      continue-on-error: false
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git checkout -b ${{ fromJson(steps.get-source-pr.outputs.data).head.ref }}-${{steps.findandreplace.outputs.result}}
        git fetch origin
        git reset --hard origin/${{ github.event.inputs.target-base-branch }}

    - name: Attempt apply all the commits from ${{ fromJson(steps.get-source-pr.outputs.data).head.ref }} to ${{ fromJson(steps.get-source-pr.outputs.data).head.ref }}-${{steps.findandreplace.outputs.result}}
      continue-on-error: false
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git cherry-pick ${{ join(fromJson(steps.get-commits.outputs.data).*.sha, ' ') }}
        git push --force --set-upstream origin ${{ fromJson(steps.get-source-pr.outputs.data).head.ref }}-${{steps.findandreplace.outputs.result}}

    - name: Get reviewers
      id: get-source-reviewers
      continue-on-error: false
      run: |
        declare -a reviewers=()
        reviewers += (${{ fromJson(steps.get-source-pr.outputs.data).requested_teams.*.login }})
        reviewers += (${{ fromJson(steps.get-source-pr.outputs.data).requested_reviewers.*.login }})
        echo "::set-output name=reviewers::reviewers"

    - name: Create pull request from ${{ fromJson(steps.get-source-pr.outputs.data).head.ref }}-${{steps.findandreplace.outputs.result}}
      uses: repo-sync/pull-request@v2.3
      with: 
        source_branch: ${{ fromJson(steps.get-source-pr.outputs.data).head.ref }}-${{steps.findandreplace.outputs.result}}
        destination_branch: ${{ github.event.inputs.target-base-branch}}
        pr_title: "🍒[${{steps.split.outputs._1}}] ${{ fromJson(steps.get-source-pr.outputs.data).title }}"
        pr_body: |
          "${{ fromJson(steps.get-source-pr.outputs.data).body }}"
          <br>
          <i>
          Automatically cherry-picked from #${{ github.event.inputs.PR-Number }} <br>
          Automation was ran by @${{ github.actor }}
          </i>
        pr_reviewer: ${{ join(steps.get-source-reviewers) }}
        pr_assignee: ${{ join(fromJson(steps.get-source-pr.outputs.data).assignees.*.login) }}
        pr_label: ${{ join(fromJson(steps.get-source-pr.outputs.data).labels.*.name) }}
        pr_allow_empty: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
